# 영화진흥위원회 데이터 수집

## setting

In [1]:
import requests

class URLMaker:
    """
    영화진흥위원회 API URL 생성 클래스
    """
    
    url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest'

    def __init__(self, key):
        """
        API key 초기화
        """
        self.key = key

    def daily_boxoffice_url(self, targetDt, itemPerPage=10, multiMovieYn='', repNationCd='', wideAreaCd=''):
        """
        일별 박스오피스 URL 생성
        """
        return f'{self.url}/boxoffice/searchDailyBoxOfficeList.json?key={self.key}&targetDt={targetDt}&itemPerPage={itemPerPage}&multiMovieYn={multiMovieYn}&repNationCd={repNationCd}&wideAreaCd={wideAreaCd}'

    def weekly_boxoffice_url(self, targetDt, weekGb='0', itemPerPage=10, multiMovieYn='', repNationCd='', wideAreaCd=''):
        """
        주간/주말 박스오피스 URL 생성
        weekGb: 0(주간), 1(주말), 2(주중)
        """
        return f'{self.url}/boxoffice/searchWeeklyBoxOfficeList.json?key={self.key}&targetDt={targetDt}&weekGb={weekGb}&itemPerPage={itemPerPage}&multiMovieYn={multiMovieYn}&repNationCd={repNationCd}&wideAreaCd={wideAreaCd}'

    def movie_list_url(self, curPage=1, itemPerPage=10, movieNm='', directorNm='', openStartDt='', openEndDt='', 
                      prdtStartYear='', prdtEndYear='', repNationCd='', movieTypeCd=''):
        """
        영화목록 URL 생성
        """
        return f'{self.url}/movie/searchMovieList.json?key={self.key}&curPage={curPage}&itemPerPage={itemPerPage}&movieNm={movieNm}&directorNm={directorNm}&openStartDt={openStartDt}&openEndDt={openEndDt}&prdtStartYear={prdtStartYear}&prdtEndYear={prdtEndYear}&repNationCd={repNationCd}&movieTypeCd={movieTypeCd}'

    def movie_info_url(self, movieCd):
        """
        영화 상세정보 URL 생성
        """
        return f'{self.url}/movie/searchMovieInfo.json?key={self.key}&movieCd={movieCd}'

    def people_list_url(self, curPage=1, itemPerPage=10, peopleNm='', filmoNames=''):
        """
        영화인목록 URL 생성
        """
        return f'{self.url}/people/searchPeopleList.json?key={self.key}&curPage={curPage}&itemPerPage={itemPerPage}&peopleNm={peopleNm}&filmoNames={filmoNames}'

    def people_info_url(self, peopleCd):
        """
        영화인 상세정보 URL 생성
        """
        return f'{self.url}/people/searchPeopleInfo.json?key={self.key}&peopleCd={peopleCd}'


    

In [4]:
MY_API_KEY = '593fd2feef1508a56b675f67d5d6189d'
url_maker = URLMaker(MY_API_KEY)


In [5]:
url_maker.key

'593fd2feef1508a56b675f67d5d6189d'

In [6]:
daily_url = url_maker.daily_boxoffice_url('20250201')
print(daily_url)


weekly_url = url_maker.weekly_boxoffice_url('20250201')
print(weekly_url)

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250201&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=
http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250201&weekGb=0&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=


## 1. 영화 상세정보 조회

- **영화 상세정보 api**를 사용합니다.
- 영화 코드(movieCd)를 입력받아 해당 영화의 상세 정보를 조회합니다.
- 다음 정보를 순서대로 출력합니다:
    - 영화 제목 (제작연도)
    - 감독 (첫 번째 감독)
    - 주연 배우 (첫 번째, 두 번째 배우)
    - 장르 (첫 번째 장르)

In [7]:
# api 가져오기

movie_detail_url = url_maker.movie_info_url('19950084')
print(movie_detail_url)

payload = {
    'key':'593fd2feef1508a56b675f67d5d6189d',
    'movieCd' : 19950084,
}

r = requests.get(movie_detail_url, params=payload)
# print(r. url)


# text와 json의 차이 / r.json은 dictionary로 바꿔줌.
#print(r. text)

movie_detail_url = r.json()

http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=593fd2feef1508a56b675f67d5d6189d&movieCd=19950084


In [8]:
# 1. 영화 상세정보 조회


detail_url = url_maker.movie_info_url('19950084')
print(detail_url)

payload = {
    'key': 'ac29ab243bc893d57bd5cb73d6784049',
    'movieCd': 19950084,
}

res = requests.get(detail_url, params=payload)
print(res.json())

def get_movie_detail(movie_cd):
    detail_dict = res.json()
    print(detail_dict['movieInfoResult']["movieInfo"]['movieNm'], '(' + detail_dict['movieInfoResult']["movieInfo"]['prdtYear'] + ')')
    #print(detail_dict['movieInfoResult']["movieInfo"]["prdtYear"])
    print('감독:',detail_dict['movieInfoResult']["movieInfo"]['directors'][0]['peopleNm'])
    print('주연:',detail_dict['movieInfoResult']["movieInfo"]['actors'][0]['peopleNm'] +',', detail_dict['movieInfoResult']["movieInfo"]['actors'][1]['peopleNm'])
    #print(detail_dict['movieInfoResult']["movieInfo"]['actors'][1]['peopleNm'])
    print('장르:',detail_dict['movieInfoResult']["movieInfo"]['genres'][0]['genreNm'])
	
get_movie_detail('19950084') #감독, 주연, 장르 등 수집하고 출력하기

http://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json?key=593fd2feef1508a56b675f67d5d6189d&movieCd=19950084
{'movieInfoResult': {'movieInfo': {'movieCd': '19950084', 'movieNm': '쇼생크 탈출', 'movieNmEn': 'The Showshank Redemption', 'movieNmOg': '', 'showTm': '142', 'prdtYear': '1994', 'openDt': '19950204', 'prdtStatNm': '개봉', 'typeNm': '장편', 'nations': [{'nationNm': '미국'}], 'genres': [{'genreNm': '드라마'}], 'directors': [{'peopleNm': '프랭크 다라본트', 'peopleNmEn': 'Frank Darabont'}], 'actors': [{'peopleNm': '팀 로빈스', 'peopleNmEn': 'Tim Robbins', 'cast': '', 'castEn': ''}, {'peopleNm': '모건 프리먼', 'peopleNmEn': 'Morgan Freeman', 'cast': '', 'castEn': ''}], 'showTypes': [{'showTypeGroupNm': '필름', 'showTypeNm': '필름'}, {'showTypeGroupNm': '2D', 'showTypeNm': '디지털'}], 'companys': [{'companyCd': '20102502', 'companyNm': '캐슬 락 엔터테인먼트', 'companyNmEn': 'Castle Rock Entertainment', 'companyPartNm': '제작사'}, {'companyCd': '20102771', 'companyNm': '콜럼비아 픽쳐스 코포레이션', 'companyNmEn': 'Columb

In [ ]:
def get_movie_detail(movie_cd):
    pass

In [ ]:
get_movie_detail('19950084')

**출력 예시**
```
쇼생크 탈출 (1994)
감독: 프랭크 다라본트
주연: 팀 로빈스, 모건 프리먼
장르: 드라마
```

## 2. 일별 박스오피스 조회

- **일별 박스오피스 api**를 사용합니다.
- 입력받은 날짜(YYYYMMDD 형식)의 박스오피스 정보를 조회합니다.
- 각 영화의 순위, 영화제목, 해당 일의 관객수를 출력합니다.

In [58]:
# 2. 일별 박스 오피스 순위

daily_url = url_maker.daily_boxoffice_url('20250201')
print(daily_url)
res = requests.get(daily_url, params=payload)
print(res.json())

def get_daily_boxoffice(target_date):
    daily_dict = res.json()
    
    print(f'{target_date} 박스오피스 TOP 10')
    
    for i in range(0, 10):
        rank = daily_dict["boxOfficeResult"]["dailyBoxOfficeList"][i]["rank"]
        name = daily_dict["boxOfficeResult"]["dailyBoxOfficeList"][i]["movieNm"]
        audience = daily_dict["boxOfficeResult"]["dailyBoxOfficeList"][i]["audiCnt"]
        
        print(f'{rank}위: {name} ({audience})')
        
get_daily_boxoffice("20250201")  # YYYYMMDD 형식으로 날짜 입력

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250201&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=
{'boxOfficeResult': {'boxofficeType': '일별 박스오피스', 'showRange': '20250201~20250201', 'dailyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '1663433100', 'salesShare': '39.5', 'salesInten': '525167660', 'salesChange': '46.1', 'salesAcc': '17240257840', 'audiCnt': '177129', 'audiInten': '40686', 'audiChange': '29.8', 'audiAcc': '1831557', 'scrnCnt': '1495', 'showCnt': '6165'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20247450', 'movieNm': '검은 수녀들', 'openDt': '2025-01-24', 'salesAmt': '934872220', 'salesShare': '22.2', 'salesInten': '247202440', 'salesChange': '35.9', 'salesAcc': '13206216740', 'audiCnt': '96043', 'audiInten': '14734', 'au

In [ ]:


def get_daily_boxoffice(target_date):
    

In [ ]:
get_daily_boxoffice("20250201")  # YYYYMMDD 형식으로 날짜 입력

**출력예시**
```
20250201 박스오피스 TOP 10
1위: 히트맨2 (177129명)
2위: 검은 수녀들 (96043명)
3위: 말할 수 없는 비밀 (63000명)
4위: 하얼빈 (23298명)
5위: 서브스턴스 (15031명)
6위: 극장판 포켓몬스터 AG: 뮤와 파동의 용사 루카리오 (12342명)
7위: 뽀로로 극장판 바닷속 대모험 (5903명)
8위: 바다 탐험대 옥토넛 어보브 앤 비욘드 : 극지방 대작전 (4570명)
9위: 극장판 짱구는 못말려: 우리들의 공룡일기 (3801명)
10위: 아이유 콘서트 : 더 위닝 (3156명)
```

## 3. 한국 영화 일별 박스오피스 조회

- **일별 박스오피스 api**를 사용합니다.
- 입력받은 날짜(YYYYMMDD 형식)의 한국 영화 박스오피스 정보를 조회합니다.
- 한국 영화만 조회하기 위해 repNationCd='K' 파라미터를 사용합니다.
- 영화가 개봉한 순서대로 정렬하여 제목, 날짜, 순위를 출력합니다.


In [67]:
# 한국 영화 일별 박스 오피스 URL 정의

daily_k_url = url_maker.daily_boxoffice_url('20250201', 10, '','K')
print(daily_k_url)

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250201&itemPerPage=10&multiMovieYn=&repNationCd=K&wideAreaCd=


In [68]:
# j.son

res = requests.get(daily_k_url, params=payload)
print(res.json())

{'boxOfficeResult': {'boxofficeType': '일별 박스오피스', 'showRange': '20250201~20250201', 'dailyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '1663433100', 'salesShare': '46.0', 'salesInten': '525167660', 'salesChange': '46.1', 'salesAcc': '17240257840', 'audiCnt': '177129', 'audiInten': '40686', 'audiChange': '29.8', 'audiAcc': '1831557', 'scrnCnt': '1495', 'showCnt': '6165'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20247450', 'movieNm': '검은 수녀들', 'openDt': '2025-01-24', 'salesAmt': '934872220', 'salesShare': '25.8', 'salesInten': '247202440', 'salesChange': '35.9', 'salesAcc': '13206216740', 'audiCnt': '96043', 'audiInten': '14734', 'audiChange': '18.1', 'audiAcc': '1363840', 'scrnCnt': '1192', 'showCnt': '4387'}, {'rnum': '3', 'rank': '3', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20223819', 'movieNm': '말할 수 없는 비밀', 'ope

In [87]:
# 3 -1 

def get_movie_details(target_date):
    daily_k_dict = res.json()
    
    print(f'{target_date} 박스오피스 (개봉일 순)')

    # 영화 리스트 가져오기
    movie_list = daily_k_dict["boxOfficeResult"]["dailyBoxOfficeList"]
    
    # 개봉일을 기준으로 정렬 (openDt 기준, 오름차순)
    sorted_movies = sorted(movie_list, key=lambda x: x["openDt"])

    # 정렬된 데이터 출력
    for movie in sorted_movies:
        name = movie["movieNm"]
        date = movie["openDt"]
        rank = movie["rank"]
        
        print(f'{name} : ({date}) - {rank}위')
        
get_movie_details("20250201")  # YYYYMMDD 형식으로 날짜 입력

20250201 박스오피스 (개봉일 순)
뜻밖의 순간 : 언익스펙티드 저니 : ( ) - 10위
마당을 나온 암탉 : (2011-07-28) - 9위
소방관 : (2024-12-04) - 8위
하얼빈 : (2024-12-24) - 4위
뽀로로 극장판 바닷속 대모험 : (2025-01-01) - 5위
히트맨2 : (2025-01-22) - 1위
검은 수녀들 : (2025-01-24) - 2위
아이유 콘서트 : 더 위닝 : (2025-01-24) - 6위
귀신경찰 : (2025-01-24) - 7위
말할 수 없는 비밀 : (2025-01-27) - 3위


In [86]:
# 3 - 2

def get_movie_details(target_date):
    daily_2_dict = res.json()
    print(f'{target_date} 한국 영화 박스오피스 (개봉일 순)')
    date_list = []
    
    for i in range(0, 10):
        name = daily_2_dict["boxOfficeResult"]["dailyBoxOfficeList"][i]["movieNm"]
        rank = daily_2_dict["boxOfficeResult"]["dailyBoxOfficeList"][i]["rank"]
        date = daily_2_dict["boxOfficeResult"]["dailyBoxOfficeList"][i]["openDt"]
        date_list.append([date, name, rank])
        
    a = sorted(date_list)
    
        #print(f'{name} : ({date}) - {rank}')
    for i in range(0, 10):
        print(f'{a[i][1]} ({a[i][0]}) - {a[i][2]}위')
        
    #print(date_list)
    
get_movie_details("20250201")  # YYYYMMDD 형식으로 날짜 입력   

20250201 한국 영화 박스오피스 (개봉일 순)
뜻밖의 순간 : 언익스펙티드 저니 ( ) - 10위
마당을 나온 암탉 (2011-07-28) - 9위
소방관 (2024-12-04) - 8위
하얼빈 (2024-12-24) - 4위
뽀로로 극장판 바닷속 대모험 (2025-01-01) - 5위
히트맨2 (2025-01-22) - 1위
검은 수녀들 (2025-01-24) - 2위
귀신경찰 (2025-01-24) - 7위
아이유 콘서트 : 더 위닝 (2025-01-24) - 6위
말할 수 없는 비밀 (2025-01-27) - 3위


**출력예시**
```
20250201 한국 영화 박스오피스 (개봉일 순)
뜻밖의 순간 : 언익스펙티드 저니 ( ) - 10위
마당을 나온 암탉 (2011-07-28) - 9위
소방관 (2024-12-04) - 8위
하얼빈 (2024-12-24) - 4위
뽀로로 극장판 바닷속 대모험 (2025-01-01) - 5위
히트맨2 (2025-01-22) - 1위
검은 수녀들 (2025-01-24) - 2위
아이유 콘서트 : 더 위닝 (2025-01-24) - 6위
귀신경찰 (2025-01-24) - 7위
말할 수 없는 비밀 (2025-01-27) - 3위
```

## 4. 1월 전체 주간 박스오피스 데이터 수집

- **주간/주말 박스오피스 api**를 사용합니다.
- 2025년 1월의 모든 주간(1/5, 1/12, 1/19, 1/26) 데이터를 수집합니다.
- 각 영화의 정보는 다음을 포함해야 합니다:
    - 영화제목, 개봉일, 누적관객수, 누적매출액
- 동일한 영화가 여러 주에 걸쳐 나타날 경우, 가장 최근의 정보만 저장합니다.


In [ ]:
(self, targetDt, weekGb='0', itemPerPage=10, multiMovieYn='', repNationCd='', wideAreaCd=''

In [163]:
daily_week1_url = url_maker.weekly_boxoffice_url('20250105')
print(daily_week1_url)

res1 = requests.get(daily_week1_url, params=payload)
print(res1.json())

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250105&weekGb=0&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=
{'boxOfficeResult': {'boxofficeType': '주간 박스오피스', 'showRange': '20241230~20250105', 'yearWeekTime': '202501', 'weeklyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20228796', 'movieNm': '하얼빈', 'openDt': '2024-12-24', 'salesAmt': '12257573810', 'salesShare': '43.2', 'salesInten': '-10357204230', 'salesChange': '-45.8', 'salesAcc': '35098771850', 'audiCnt': '1287622', 'audiInten': '-1074841', 'audiChange': '-45.5', 'audiAcc': '3672922', 'scrnCnt': '1847', 'showCnt': '46414'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20200142', 'movieNm': '소방관', 'openDt': '2024-12-04', 'salesAmt': '3151980440', 'salesShare': '11.1', 'salesInten': '-2661254850', 'salesChange': '-45.8', 'salesAcc': '33400749550

In [164]:
daily_week2_url = url_maker.weekly_boxoffice_url('20250112')
print(daily_week2_url)

res2 = requests.get(daily_week2_url, params=payload)
print(res2.json())

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250112&weekGb=0&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=
{'boxOfficeResult': {'boxofficeType': '주간 박스오피스', 'showRange': '20250106~20250112', 'yearWeekTime': '202502', 'weeklyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20228796', 'movieNm': '하얼빈', 'openDt': '2024-12-24', 'salesAmt': '4878365560', 'salesShare': '36.7', 'salesInten': '-7379208250', 'salesChange': '-60.2', 'salesAcc': '39977137410', 'audiCnt': '507470', 'audiInten': '-780152', 'audiChange': '-60.6', 'audiAcc': '4180392', 'scrnCnt': '1322', 'showCnt': '34334'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20200142', 'movieNm': '소방관', 'openDt': '2024-12-04', 'salesAmt': '1435787980', 'salesShare': '10.8', 'salesInten': '-1716192460', 'salesChange': '-54.4', 'salesAcc': '34836537530', '

In [165]:
daily_week3_url = url_maker.weekly_boxoffice_url('20250119')
print(daily_week3_url)

res3 = requests.get(daily_week3_url, params=payload)
print(res3.json())

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250119&weekGb=0&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=
{'boxOfficeResult': {'boxofficeType': '주간 박스오피스', 'showRange': '20250113~20250119', 'yearWeekTime': '202503', 'weeklyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20228796', 'movieNm': '하얼빈', 'openDt': '2024-12-24', 'salesAmt': '3028736420', 'salesShare': '32.8', 'salesInten': '-1849629140', 'salesChange': '-37.9', 'salesAcc': '43005873830', 'audiCnt': '315306', 'audiInten': '-192164', 'audiChange': '-37.9', 'audiAcc': '4495698', 'scrnCnt': '1160', 'showCnt': '29450'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20200142', 'movieNm': '소방관', 'openDt': '2024-12-04', 'salesAmt': '983416200', 'salesShare': '10.6', 'salesInten': '-452371780', 'salesChange': '-31.5', 'salesAcc': '35819953730', 'au

In [166]:
daily_week4_url = url_maker.weekly_boxoffice_url('20250126')
print(daily_week4_url)

res4 = requests.get(daily_week4_url, params=payload)
print(res4.json())

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250126&weekGb=0&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=
{'boxOfficeResult': {'boxofficeType': '주간 박스오피스', 'showRange': '20250120~20250126', 'yearWeekTime': '202504', 'weeklyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'NEW', 'movieCd': '20247450', 'movieNm': '검은 수녀들', 'openDt': '2025-01-24', 'salesAmt': '5870106460', 'salesShare': '33.3', 'salesInten': '5870106460', 'salesChange': '100.0', 'salesAcc': '5870106460', 'audiCnt': '606145', 'audiInten': '606145', 'audiChange': '100.0', 'audiAcc': '606145', 'scrnCnt': '1662', 'showCnt': '21820'}, {'rnum': '2', 'rank': '2', 'rankInten': '25', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '5656681120', 'salesShare': '32.1', 'salesInten': '5628592120', 'salesChange': '20038.4', 'salesAcc': '5686993120', 

In [167]:
def get_weekly_boxoffice():
    daily_week1_dict = res1.json()
    
    result = {}

    i = 0

    movie = daily_week1_dict[j]
    ["boxOfficeResult"]["weeklyBoxOfficeList"]
    
    while i < len(movie):
        a = movie[i]
        
        
        info = {f'영화제목: {a['movieNm']},개봉일: {a['openDt']},누적관객: {a['showCnt']},누적매출: {a['salesAcc']}'}
        result[a['movieNm']] = info
        
        i += 1


    
    print(result)    

In [190]:
def get_weekly_boxoffice():

    r = [res1,res2,res3,res4]
    daily_week_dict = [{} for _ in range(4)] 
    #daily_week_dict = [daily_week1_dict, daily_week2_dict, daily_week3_dict, daily_week4_url]

    result = {}
    for i in range(4):
        
        daily_week_dict[i] = r[i].json()
        
    
        movies = daily_week_dict[i]["boxOfficeResult"]["weeklyBoxOfficeList"]
    
        j = 0
        while j < len(movies):
            movie = movies[j]
            
            info = {f'영화제목: {movie['movieNm']},개봉일: {movie['openDt']},누적관객: {movie['showCnt']},누적매출: {movie['salesAcc']}'}
            result[movie['movieNm']] = info
                
            j += 1
    
    
        
    print(result)    

In [191]:
get_weekly_boxoffice()

{'하얼빈': {'영화제목: 하얼빈,개봉일: 2024-12-24,누적관객: 15465,누적매출: 44407362460'}, '소방관': {'영화제목: 소방관,개봉일: 2024-12-04,누적관객: 6026,누적매출: 36145572270'}, '보고타: 마지막 기회의 땅': {'영화제목: 보고타: 마지막 기회의 땅,개봉일: 2024-12-31,누적관객: 9611,누적매출: 3669720540'}, '수퍼 소닉3': {'영화제목: 수퍼 소닉3,개봉일: 2025-01-01,누적관객: 5070,누적매출: 2950620910'}, '뽀로로 극장판 바닷속 대모험': {'영화제목: 뽀로로 극장판 바닷속 대모험,개봉일: 2025-01-01,누적관객: 2372,누적매출: 2996015770'}, '무파사: 라이온 킹': {'영화제목: 무파사: 라이온 킹,개봉일: 2024-12-18,누적관객: 2943,누적매출: 8188072950'}, '모아나 2': {'영화제목: 모아나 2,개봉일: 2024-11-27,누적관객: 2595,누적매출: 32533317750'}, '극장판 짱구는 못말려: 우리들의 공룡일기': {'영화제목: 극장판 짱구는 못말려: 우리들의 공룡일기,개봉일: 2024-12-18,누적관객: 2374,누적매출: 7177275100'}, '위키드': {'영화제목: 위키드,개봉일: 2024-11-20,누적관객: 2954,누적매출: 21677201940'}, '시빌 워: 분열의 시대': {'영화제목: 시빌 워: 분열의 시대,개봉일: 2024-12-31,누적관객: 6364,누적매출: 836845230'}, '동화지만 청불입니다': {'영화제목: 동화지만 청불입니다,개봉일: 2025-01-08,누적관객: 8453,누적매출: 1465916720'}, '서브스턴스': {'영화제목: 서브스턴스,개봉일: 2024-12-11,누적관객: 2874,누적매출: 2954609400'}, '검은 수녀들': {'영화제목: 검은 수녀들,개봉일: 2025-01-24,누적관객: 21820,누적매출: 

**출력예시**
```
{'하얼빈': {'영화제목': '하얼빈', '개봉일': '2024-12-24', '누적관객': '4642215', '누적매출': '44407362460'}, '소방관': {'영화제목': '소방관', '개봉일': '2024-12-04', '누적관객': '3840551', '누적매출': '36145572270'}, '보고타: 마지막 기회의 땅': {'영화제목': '보고타: 마지막 기회의 땅', '개봉일': '2024-12-31', '누적관객': '396287', '누적매출': '3669720540'}, '수퍼 소닉3': {'영화제목': '수퍼 소닉3', '개봉일': '2025-01-01', '누적관객': '322100', '누적매출': '2950620910'}, '뽀로로 극장판 바닷속 대모험': {'영화제목': '뽀로로 극장판 바닷속 대모험', '개봉일': '2025-01-01', '누적관객': '349597', '누적매출': '2996015770'}, '무파사: 라이온 킹': {'영화제목': '무파사: 라이온 킹', '개봉일': '2024-12-18', '누적관객': '833832', '누적매출': '8188072950'}, '모아나 2': {'영화제목': '모아나 2', '개봉일': '2024-11-27', '누적관객': '3522517', '누적매출': '32533317750'}, '극장판 짱구는 못말려: 우리들의 공룡일기': {'영화제목': '극장판 짱구는 못말려: 우리들의 공룡일기', '개봉일': '2024-12-18', '누적관객': '762895', '누적매출': '7177275100'}, '위키드': {'영화제목': '위키드', '개봉일': '2024-11-20', '누적관객': '2195165', '누적매출': '21677201940'}, '시빌 워: 분열의 시대': {'영화제목': '시빌 워: 분열의 시대', '개봉일': '2024-12-31', '누적관객': '80373', '누적매출': '836845230'}, '동화지만 청불입니다': {'영화제목': '동화지만 청불입니다', '개봉일': '2025-01-08', '누적관객': '157616', '누적매출': '1465916720'}, '서브스턴스': {'영화제목': '서브스턴스', '개봉일': '2024-12-11', '누적관객': '302870', '누적매출': '2954609400'}, '검은 수녀들': {'영화제목': '검은 수녀들', '개봉일': '2025-01-24', '누적관객': '606145', '누적매출': '5870106460'}, '히트맨2': {'영화제목': '히트맨2', '개봉일': '2025-01-22', '누적관객': '604875', '누적매출': '5686993120'}, '극장판 포켓몬스터 AG: 뮤와 파동의 용사 루카리오': {'영화제목': '극장판 포켓몬스터 AG: 뮤와 파동의 용사 루카리오', '개봉일': '2025-01-22', '누적관객': '64585', '누적매출': '570033160'}, '아이유 콘서트 : 더 위닝': {'영화제목': '아이유 콘서트 : 더 위닝', '개봉일': '2025-01-24', '누적관객': '28061', '누적매출': '778067000'}, '귀신경찰': {'영화제목': '귀신경찰', '개봉일': '2025-01-24', '누적관객': '21949', '누적매출': '191035980'}}
```

## 5. 일별 박스오피스 영화의 상세정보

- **일별 박스오피스 api**와 **영화 상세정보 api**를 사용합니다.
- 입력받은 날짜의 일별 박스오피스 TOP 10을 조회합니다.
- 각 영화의 상세 정보를 추가로 조회하여 다음 정보를 출력합니다:
    - 순위
    - 영화제목
    - 감독
    - 주연배우 (최대 3명)

In [192]:
daily_url = url_maker.daily_boxoffice_url('20250201')
print(daily_url)
res = requests.get(daily_url, params=payload)
print(res.json())

http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=593fd2feef1508a56b675f67d5d6189d&targetDt=20250201&itemPerPage=10&multiMovieYn=&repNationCd=&wideAreaCd=
{'boxOfficeResult': {'boxofficeType': '일별 박스오피스', 'showRange': '20250201~20250201', 'dailyBoxOfficeList': [{'rnum': '1', 'rank': '1', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20233006', 'movieNm': '히트맨2', 'openDt': '2025-01-22', 'salesAmt': '1663433100', 'salesShare': '39.5', 'salesInten': '525167660', 'salesChange': '46.1', 'salesAcc': '17240257840', 'audiCnt': '177129', 'audiInten': '40686', 'audiChange': '29.8', 'audiAcc': '1831557', 'scrnCnt': '1495', 'showCnt': '6165'}, {'rnum': '2', 'rank': '2', 'rankInten': '0', 'rankOldAndNew': 'OLD', 'movieCd': '20247450', 'movieNm': '검은 수녀들', 'openDt': '2025-01-24', 'salesAmt': '934872220', 'salesShare': '22.2', 'salesInten': '247202440', 'salesChange': '35.9', 'salesAcc': '13206216740', 'audiCnt': '96043', 'audiInten': '14734', 'au

In [ ]:
def get_movie_details(target_date):
    pass

In [ ]:
get_movie_details("20250201")  # YYYYMMDD 형식으로 날짜 입력

**출력예시**

```
1위
히트맨2
감독: 최원섭
주연: 권상우, 정준호, 이이경
----------------------------------------

2위
검은 수녀들
감독: 권혁재
주연: 송혜교, 전여빈, 이진욱
----------------------------------------

3위
말할 수 없는 비밀
감독: 서유민
주연: 도경수, 원진아, 신예은
----------------------------------------
...
```

## 6. 배우검색

- **영화인목록 api**, **영화인 상세정보 api**, **영화 상세정보 api**를 사용합니다.
- 배우 이름을 입력받아 해당 배우의 정보를 검색합니다.
- 여러 명의 동명 배우가 있는 경우, 필모그래피가 가장 많은 배우를 선택합니다.
- 선택된 배우의 출연작 중 '배우'로 참여한 작품 5개의 정보를 출력합니다:
    - 영화 제목
    - 개봉일
    - 상영시간
    - 감독

In [ ]:
def analyze_actor_movies(actor_name):
    pass

In [ ]:
analyze_actor_movies("박정민")  # 원하는 배우 이름으로 변경 가능

**출력예시**

```
배우 '박정민'의 최근 출연작 5개

제목: 하얼빈
개봉일: 20241224
상영시간: 113분
감독: 우민호

제목: 얼굴
개봉일: 
상영시간: 분
감독: 연상호

제목: 전, 란
개봉일: 
상영시간: 126분
감독: 김상만

제목: 휴민트
개봉일: 
상영시간: 분
감독: 류승완

제목: 밀수
개봉일: 20230726
상영시간: 129분
감독: 류승완
```

In [ ]:
 http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json

? (파라미터 추가하기 전)

key == cc1213 (키,벨류쌍)

&

targetDt = 20250201 (키,벨류쌍)

& 